<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-19N1NVEG" ignored="2" name="Test" tests="2" failures="1" timestamp="22 Mar 2021 13:34:27 GMT" time="114.389" errors="0">
  <testcase name="DemoElements_demoElementTestcase" time="45.059" classname="TestCases.DemoElements"/>
  <testcase name="HRM_ApplyLeave" time="61.231" classname="TestCases.HRM">
    <failure type="BasePack.TestExceptions" message="Failure during test execution in the process [Apply Leave]">
      <![CDATA[BasePack.TestExceptions: Failure during test execution in the process [Apply Leave]
at Reusables.Keywords.addReport(Keywords.java:497)
at Pages.ApplyLeavePage.ApplyLeave(ApplyLeavePage.java:25)
at TestCases.HRM.HRM_ApplyLeave(HRM.java:22)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- HRM_ApplyLeave -->
  <testcase name="@BeforeSuite onStart" time="0.0" classname="BasePack.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite onStart -->
  <testcase name="@AfterSuite onFinish" time="0.0" classname="BasePack.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite onFinish -->
</testsuite> <!-- Test -->
